version: '3.4'

services:
  gqlgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;
    ports:
      - "5000:5000"

  tagswebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003;
    ports:
      - "5003:5003"
    expose:
      - '5003'
